ALTER TABLE "workspaces" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "workspace_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "threads" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "workflows" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "plans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "plan_steps" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "run_activities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "approval_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "invites" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "thread_shares" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "workspace_api_keys" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "workspaces_select" ON "workspaces" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("workspaces"."created_by" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspaces"."id" and wm."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "workspaces_insert" ON "workspaces" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("workspaces"."created_by" = auth.uid());--> statement-breakpoint
CREATE POLICY "workspaces_update" ON "workspaces" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("workspaces"."created_by" = auth.uid());--> statement-breakpoint
CREATE POLICY "workspaces_delete" ON "workspaces" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("workspaces"."created_by" = auth.uid());--> statement-breakpoint
CREATE POLICY "groups_select" ON "groups" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("groups"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "groups"."workspace_id" and wm."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "groups_insert" ON "groups" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("groups"."user_id" = auth.uid() and exists (select 1 from "workspace_members" wm where wm."workspace_id" = "groups"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "groups_update" ON "groups" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("groups"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "groups"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "groups_delete" ON "groups" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("groups"."kind" = 'custom' and ("groups"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "groups"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor'))));--> statement-breakpoint
CREATE POLICY "workspace_members_select" ON "workspace_members" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_members"."workspace_id" and wm."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "workspace_members_insert" ON "workspace_members" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_members"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "workspace_members_update" ON "workspace_members" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_members"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "workspace_members_delete" ON "workspace_members" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_members"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')) and "workspace_members"."role" != 'owner');--> statement-breakpoint
CREATE POLICY "user_profiles_select" ON "user_profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("user_profiles"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "user_profiles_insert" ON "user_profiles" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("user_profiles"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "user_profiles_update" ON "user_profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("user_profiles"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "user_profiles_delete" ON "user_profiles" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("user_profiles"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "threads_select" ON "threads" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "threads"."id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "threads"."id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "threads_insert" ON "threads" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("threads"."user_id" = auth.uid() and exists (select 1 from "workspace_members" wm where wm."workspace_id" = "threads"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "threads_update" ON "threads" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "threads"."id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "threads_delete" ON "threads" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("threads"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "workflows_select" ON "workflows" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("workflows"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workflows"."workspace_id" and wm."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "workflows_insert" ON "workflows" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("workflows"."user_id" = auth.uid() and exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workflows"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "workflows_update" ON "workflows" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("workflows"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workflows"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "workflows_delete" ON "workflows" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("workflows"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "plans_select" ON "plans" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plans"."workflow_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "plans_insert" ON "plans" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plans"."workflow_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "plans_update" ON "plans" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plans"."workflow_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "plans_delete" ON "plans" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plans"."workflow_id" and w."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "plan_steps_select" ON "plan_steps" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plan_steps"."plan_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "plan_steps_insert" ON "plan_steps" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plan_steps"."plan_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "plan_steps_update" ON "plan_steps" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plan_steps"."plan_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "plan_steps_delete" ON "plan_steps" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "plans" p join "workflows" w on w."id" = p."workflow_id" where p."id" = "plan_steps"."plan_id" and w."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "chat_messages_select" ON "chat_messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "chat_messages"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "chat_messages"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "chat_messages_insert" ON "chat_messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "threads" t where t."id" = "chat_messages"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "chat_messages"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "chat_messages_update" ON "chat_messages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("chat_messages"."user_id" = auth.uid() or exists (select 1 from "threads" t where t."id" = "chat_messages"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "chat_messages_delete" ON "chat_messages" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("chat_messages"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "runs_select" ON "runs" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "runs"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "runs"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "runs_insert" ON "runs" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "threads" t where t."id" = "runs"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "runs"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "runs_update" ON "runs" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("runs"."user_id" = auth.uid() or exists (select 1 from "threads" t where t."id" = "runs"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
CREATE POLICY "runs_delete" ON "runs" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("runs"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "run_activities_select" ON "run_activities" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "runs" r where r."id" = "run_activities"."run_id" and exists (select 1 from "threads" t where t."id" = r."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = r."thread_id" and ts."user_id" = auth.uid())))));--> statement-breakpoint
CREATE POLICY "approval_requests_select" ON "approval_requests" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "approval_requests"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "approval_requests"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "approval_requests_insert" ON "approval_requests" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "threads" t where t."id" = "approval_requests"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "approval_requests"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "approval_requests_update" ON "approval_requests" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "approval_requests"."thread_id" and (t."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = t."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "approval_requests"."thread_id" and ts."user_id" = auth.uid()))));--> statement-breakpoint
CREATE POLICY "invites_select" ON "invites" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("invites"."invited_by" = auth.uid() or "invites"."invited_user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "invites"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "invites_insert" ON "invites" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("invites"."invited_by" = auth.uid());--> statement-breakpoint
CREATE POLICY "invites_update" ON "invites" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("invites"."invited_by" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "invites"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "invites_delete" ON "invites" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("invites"."invited_by" = auth.uid());--> statement-breakpoint
CREATE POLICY "thread_shares_select" ON "thread_shares" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "thread_shares"."thread_id" and t."user_id" = auth.uid()) or "thread_shares"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "thread_shares_insert" ON "thread_shares" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "threads" t where t."id" = "thread_shares"."thread_id" and t."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "thread_shares_delete" ON "thread_shares" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "threads" t where t."id" = "thread_shares"."thread_id" and t."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "notifications_select" ON "notifications" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("notifications"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "notifications_insert" ON "notifications" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("notifications"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "notifications_update" ON "notifications" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("notifications"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "notifications_delete" ON "notifications" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("notifications"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "workspace_api_keys_select" ON "workspace_api_keys" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_api_keys"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "workspace_api_keys_insert" ON "workspace_api_keys" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_api_keys"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')) and "workspace_api_keys"."created_by" = auth.uid());--> statement-breakpoint
CREATE POLICY "workspace_api_keys_update" ON "workspace_api_keys" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_api_keys"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "workspace_api_keys_delete" ON "workspace_api_keys" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "workspace_members" wm where wm."workspace_id" = "workspace_api_keys"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
CREATE POLICY "files_select" ON "files" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("files"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "files"."workspace_id" and wm."user_id" = auth.uid()));--> statement-breakpoint
CREATE POLICY "files_insert" ON "files" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("files"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "files_update" ON "files" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("files"."user_id" = auth.uid());--> statement-breakpoint
CREATE POLICY "files_delete" ON "files" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("files"."user_id" = auth.uid());