ALTER POLICY "workspace_members_select" ON "workspace_members" TO authenticated USING ("workspace_members"."user_id" = auth.uid());--> statement-breakpoint
ALTER POLICY "workspace_members_insert" ON "workspace_members" TO authenticated WITH CHECK (exists (select 1 from "workspaces" w where w."id" = "workspace_members"."workspace_id" and w."created_by" = auth.uid()));--> statement-breakpoint
ALTER POLICY "workspace_members_update" ON "workspace_members" TO authenticated USING (exists (select 1 from "workspaces" w where w."id" = "workspace_members"."workspace_id" and w."created_by" = auth.uid())) WITH CHECK (exists (select 1 from "workspaces" w where w."id" = "workspace_members"."workspace_id" and w."created_by" = auth.uid()));--> statement-breakpoint
ALTER POLICY "workspace_members_delete" ON "workspace_members" TO authenticated USING (exists (select 1 from "workspaces" w where w."id" = "workspace_members"."workspace_id" and w."created_by" = auth.uid()) and "workspace_members"."role" != 'owner');--> statement-breakpoint
ALTER POLICY "threads_select" ON "threads" TO authenticated USING ("threads"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "threads"."workspace_id" and wm."user_id" = auth.uid()) or exists (select 1 from "thread_shares" ts where ts."thread_id" = "threads"."id" and ts."user_id" = auth.uid()));--> statement-breakpoint
ALTER POLICY "threads_update" ON "threads" TO authenticated USING ("threads"."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = "threads"."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')));--> statement-breakpoint
ALTER POLICY "plans_select" ON "plans" TO authenticated USING (exists (select 1 from "workflows" w where w."id" = "plans"."workflow_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid()))));--> statement-breakpoint
ALTER POLICY "plans_insert" ON "plans" TO authenticated WITH CHECK (exists (select 1 from "workflows" w where w."id" = "plans"."workflow_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
ALTER POLICY "plans_update" ON "plans" TO authenticated USING (exists (select 1 from "workflows" w where w."id" = "plans"."workflow_id" and (w."user_id" = auth.uid() or exists (select 1 from "workspace_members" wm where wm."workspace_id" = w."workspace_id" and wm."user_id" = auth.uid() and wm."role" in ('owner', 'editor')))));--> statement-breakpoint
ALTER POLICY "plans_delete" ON "plans" TO authenticated USING (exists (select 1 from "workflows" w where w."id" = "plans"."workflow_id" and w."user_id" = auth.uid()));